apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-service
  name: connection-service
spec:
  ports:
  - name: "5053"
    port: 5053
    targetPort: 5053
  - name: "5063"
    port: 5063
    targetPort: 5063
  selector:
    service: connection-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-service
  name: connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-service
  template:
    metadata:
      labels:
        service: connection-service
    spec:
      containers:
      - image: rolak/connection-service:latest
        name: connection-service
        imagePullPolicy: Always
        env:
        - name: GRPC_LOCATION_TARGET
          value: "location-service:5061"
        - name: GRPC_PERSON_TARGET
          value: "person-service:5062"
        - name: GRPC_CONNECTIONS_TARGET
          value: "connection-service:5063"
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: TOPIC_NAME
          value: "locations"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
