apiVersion: v1
kind: Service
metadata:
  labels:
    service: create-location-service
  name: create-location-service
spec:
  ports:
  - name: "5050"
    port: 5050
    targetPort: 5050
  selector:
    service: create-location-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: create-location-service
  name: create-location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: create-location-service
  template:
    metadata:
      labels:
        service: create-location-service
    spec:
      containers:
      - image: rolak/create-location-service:latest
        name: create-location-service
        imagePullPolicy: Always
        env:
        - name: GRPC_LOCATION_TARGET
          value: "location-service:5061"
        - name: GRPC_PERSON_TARGET
          value: "person-service:5062"
        - name: GRPC_CONNECTIONS_TARGET
          value: "connection-service:5063"
        - name: KAFKA_SERVER
          value: "kafka:9093"
        - name: TOPIC_NAME
          value: "locations"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
